build:
	javac -classpath lib/zookeeper-3.3.2.jar:lib/log4j-1.2.15.jar ZkConnector.java fileServer.java fileServerListener.java MD5Test.java
run:
	java -classpath lib/zookeeper-3.3.2.jar:lib/log4j-1.2.15.jar:. fileServer
clean:
	rm -f *.class
